server:
    port: 8081
spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: olviehubert@gmail.com
        password: eqirdytzzinfthdp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true