use insurance;
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('001', 'BHXH Tp. Hà Nội', 'Địa chỉ Hà Nội', '123456789');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('002', 'BHXH Tỉnh Hà Giang', 'Địa chỉ Hà Giang', '987654321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('003', 'BHXH Tỉnh Cao Bằng', 'Địa chỉ Cao Bằng', '654321789');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('004', 'BHXH Tỉnh Bắc Kạn', 'Địa chỉ Bắc Kạn', '321987654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('005', 'BHXH Tỉnh Tuyên Quang', 'Địa chỉ Tuyên Quang', '789654321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('006', 'BHXH Tỉnh Lào Cai', 'Địa chỉ Lào Cai', '456321987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('007', 'BHXH Tỉnh Điện Biên', 'Địa chỉ Điện Biên', '987654123');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('008', 'BHXH Tỉnh Lai Châu', 'Địa chỉ Lai Châu', '789123456');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('009', 'BHXH Tỉnh Sơn La', 'Địa chỉ Sơn La', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('010', 'BHXH Tỉnh Yên Bái', 'Địa chỉ Yên Bái', '321789654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('011', 'BHXH Tỉnh Hòa Bình', 'Địa chỉ Hòa Bình', '456987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('012', 'BHXH Tỉnh Thái Nguyên', 'Địa chỉ Thái Nguyên', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('013', 'BHXH Tỉnh Lạng Sơn', 'Địa chỉ Lạng Sơn', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('014', 'BHXH Tỉnh Quảng Ninh', 'Địa chỉ Quảng Ninh', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('015', 'BHXH Tỉnh Bắc Giang', 'Địa chỉ Bắc Giang', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('016', 'BHXH Tỉnh Phú Thọ', 'Địa chỉ Phú Thọ', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('017', 'BHXH Tỉnh Vĩnh Phúc', 'Địa chỉ Vĩnh Phúc', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('018', 'BHXH Tỉnh Bắc Ninh', 'Địa chỉ Bắc Ninh', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('019', 'BHXH Tỉnh Hải Dương', 'Địa chỉ Hải Dương', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('020', 'BHXH TP Hải Phòng', 'Địa chỉ Hải Phòng', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('021', 'BHXH tỉnh Hưng Yên', 'Địa chỉ Hưng Yên', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('022', 'BHXH Tỉnh Thái Bình', 'Địa chỉ Thái Bình', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('023', 'BHXH Tỉnh Hà Nam', 'Địa chỉ Hà Nam', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('024', 'BHXH Tỉnh Nam Định', 'Địa chỉ Nam Định', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('025', 'BHXH Tỉnh Ninh Bình', 'Địa chỉ Ninh Bình', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('026', 'BHXH Tỉnh Thanh Hoá', 'Địa chỉ Thanh Hoá', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('027', 'BHXH Tỉnh Nghệ An', 'Địa chỉ Nghệ An', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('028', 'BHXH Tỉnh Hà Tĩnh', 'Địa chỉ Hà Tĩnh', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('029', 'BHXH Tỉnh Quảng Bình', 'Địa chỉ Quảng Bình', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('030', 'BHXH Tỉnh Quảng Trị', 'Địa chỉ Quảng Trị', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('031', 'BHXH Tỉnh TT-Huế', 'Địa chỉ TT-Huế', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('032', 'BHXH TP Đà Nẵng', 'Địa chỉ TP Đà Nẵng', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('033', 'BHXH Tỉnh Quảng Nam', 'Địa chỉ Quảng Nam', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('034', 'BHXH Tỉnh Quảng Ngãi', 'Địa chỉ Quảng Ngãi', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('035', 'BHXH Tỉnh Bình Định', 'Địa chỉ Bình Định', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('036', 'BHXH Tỉnh Phú Yên', 'Địa chỉ Phú Yên', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('037', 'BHXH Tỉnh Khánh Hoà', 'Địa chỉ Khánh Hoà', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('038', 'BHXH Tỉnh Ninh Thuận', 'Địa chỉ Ninh Thuận', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('039', 'BHXH Tỉnh Bình Thuận', 'Địa chỉ Bình Thuận', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('040', 'BHXH Tỉnh Kon Tum', 'Địa chỉ Kon Tum', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('041', 'BHXH Tỉnh Gia Lai', 'Địa chỉ Gia Lai', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('042', 'BHXH Tỉnh Đắk Lắk', 'Địa chỉ Đắk Lắk', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('043', 'BHXH Tỉnh Đắk Nông', 'Địa chỉ Đắk Nông', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('044', 'BHXH Tỉnh Lâm Đồng', 'Địa chỉ Lâm Đồng', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('045', 'BHXH Tỉnh Bình Phước', 'Địa chỉ Bình Phước', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('046', 'BHXH Tỉnh Tây Ninh', 'Địa chỉ Tây Ninh', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('047', 'BHXH Tỉnh Bình Dương', 'Địa chỉ Bình Dương', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('048', 'BHXH Tỉnh Đồng Nai', 'Địa chỉ Đồng Nai', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('049', 'BHXH Tỉnh Bà Rịa - Vũng Tàu', 'Địa chỉ Bà Rịa - Vũng Tàu', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('050', 'BHXH Tp. Hồ Chí Minh', 'Địa chỉ TP Hồ Chí Minh', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('051', 'BHXH Tỉnh Long An', 'Địa chỉ Long An', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('052', 'BHXH Tỉnh Tiền Giang', 'Địa chỉ Tiền Giang', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('053', 'BHXH Tỉnh Bến Tre', 'Địa chỉ Bến Tre', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('054', 'BHXH Tỉnh Trà Vinh', 'Địa chỉ Trà Vinh', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('055', 'BHXH Tỉnh Vĩnh Long', 'Địa chỉ Vĩnh Long', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('056', 'BHXH Tỉnh Đồng Tháp', 'Địa chỉ Đồng Tháp', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('057', 'BHXH Tỉnh An Giang', 'Địa chỉ An Giang', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('058', 'BHXH Tỉnh Kiên Giang', 'Địa chỉ Kiên Giang', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('059', 'BHXH Tp. Cần Thơ', 'Địa chỉ TP Cần Thơ', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('060', 'BHXH Tỉnh Hậu Giang', 'Địa chỉ Hậu Giang', '987321654');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('061', 'BHXH Tỉnh Sóc Trăng', 'Địa chỉ Sóc Trăng', '654987321');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('062', 'BHXH Tỉnh Bạc Liêu', 'Địa chỉ Bạc Liêu', '321654987');
INSERT INTO insurance_agency (id, name, address, account_number) VALUES ('063', 'BHXH Tỉnh Cà Mau', 'Địa chỉ Cà Mau', '987321654');
